host_url = "http://localhost:5000"
executive_producer_headers = {
    "Authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ikg4UlMtbXlmM0lyaTFWM3k3QjRiWiJ9.eyJpc3MiOiJodHRwczovL2NsYXNzdWRhY2l0eS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWViMDdmOTIxY2MxYWMwYzE0ODRlZDczIiwiYXVkIjoiY2FzdGluZyIsImlhdCI6MTU5MDY5NTM5MiwiZXhwIjoxNTkwNzAyNTkyLCJhenAiOiJLNUtVNkFSdUpLVTRqRUtNSmM1NmtiekM0d0dGRGZaOCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsImRlbGV0ZTptb3ZpZXMiLCJnZXQ6YWN0b3JzIiwiZ2V0Om1vdmllcyIsInBhdGNoOmFjdG9ycyIsInBhdGNoOm1vdmllcyIsInBvc3Q6YWN0b3JzIiwicG9zdDptb3ZpZXMiXX0.k-7sIp3fUbE1tYi3n3TMR9pCIavgXaTFcyJLvtnmlPDG6uycHw9QCcM9LTHVPfueSiKLWmhMwqSovYBKC9EEjt-n2j6kOl8L4_EgBXdbkUnCUfCj69SYc6fg9xrXWB5QQGK55hRobZbV_qR1XMsrSKKNuEniow2JPCYy5oe9JpKlydlHfte92W1CbbY5Qx-jQnRYK4X9nHMPt9bNzSmjWNNXsBVlJUKJXFGTo8_Vl6OGUwKEWqu3MP_tcJUcWx1kZZ5v-aMAtpNJjIbXwwu0bnEQlTgnnQmXXHyQ7U13iTc1Guc0gB31-AsYs5Awmy3AQE6Ef4PFT-9oMMbr-k6Fiw",
    "Content-Type": "application/json"
}

casting_director_headers = {
    "Authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ikg4UlMtbXlmM0lyaTFWM3k3QjRiWiJ9.eyJpc3MiOiJodHRwczovL2NsYXNzdWRhY2l0eS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWViNWJhOGM2YjY5YmMwYzEyMDQ2Y2QxIiwiYXVkIjoiY2FzdGluZyIsImlhdCI6MTU5MDY5NDMzMiwiZXhwIjoxNTkwNzAxNTMyLCJhenAiOiJLNUtVNkFSdUpLVTRqRUtNSmM1NmtiekM0d0dGRGZaOCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOltdfQ.pATHwpHPDEpJsOXOBTNTtZ1lCEP87bqSmmC-svrSdgXO5J6TcUm9EVjgxVKPF-oqdI-arb57U70hWxkHJeryxzQrOlWxhbdDzDihpfks-UZrbLpv_iRcWP1noldKft4rgW8Yj5voFH0GlgCuRwevbZAE9fn1VzDMyzwRFyKY8K71HZ-c0xjC0nrArdOpe0vM5J9jPCQFHgGVhMg7yO27P5BzOdqergqvvLoOVTs8Yn7PkOSTDXKpwmFBVZmpTJjrn1uJqvVEFpJx5-liOFJHsoKck2ahFEvJq9U5HadxGKm-p7MzACu4phx5QhNZxneSWOvFUHh2In3PZfr0YY7SJA",
    "Content-Type": "application/json"
}

casting_assistant_headers = {
    "Authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ikg4UlMtbXlmM0lyaTFWM3k3QjRiWiJ9.eyJpc3MiOiJodHRwczovL2NsYXNzdWRhY2l0eS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWVjZmY2NTM2ZGFiZGYwYzBkMjBjMjQwIiwiYXVkIjoiY2FzdGluZyIsImlhdCI6MTU5MDY5NDExMywiZXhwIjoxNTkwNzAxMzEzLCJhenAiOiJLNUtVNkFSdUpLVTRqRUtNSmM1NmtiekM0d0dGRGZaOCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZ2V0OmFjdG9ycyIsImdldDptb3ZpZXMiXX0.Y-KUUuxYtZqlkgJpeROAdhIkMDj7hPlfdsQcm7VZr7yhDkI9Wr0uDQfOhfHsIO_uOl7qV0aUnTMuWk4FDUq_NPOuMAG4_nloRXORoGfkp-f7tyJskD0mwcCTwT8Kgt8rTB9fIsIAMDrMiqIeRJvbLuNnQ6bYoxmHp0UlDhchvoAp-y70AzKTn8peDdoWEbmEYx8aCVBC_LATbAycwUdhK7ZnZVKrsCjvSNAb3MX8Bw2nPz6om8Hgz7yFxchiHFkQ94nLJE6XQw9fozUl72Wj7FHo7lSiAdizgrWjSoW8DEHHrxCHdbPPPyt8AusLeltVvR0hkidCLkBYIKKDDbAHlg",
    "Content-Type": "application/json"
}