export AUTH0_DOMAIN="classudacity.auth0.com"
export AUDIENCE="casting"
export CLIENT_ID="K5KU6ARuJKU4jEKMJc56kbzC4wGFDfZ8"
export REDIRECT_URL="https://127.0.0.1:8080/"
export JWT_SECRET="V8yTNCj8-KXKoSkoRyHNxVgD4R3GistfWN_MWuc--far9cBDrjrGK_VeUiDRXz3f"
