"""empty message

Revision ID: 8546009b8167
Revises: 32f5bbce2c43
Create Date: 2020-05-26 10:08:08.036675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8546009b8167'
down_revision = '32f5bbce2c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_movie',
        sa.Column('actor_id',
                  sa.Integer().with_variant(sa.Integer(), 'sqlite'),
                  nullable=False),
        sa.Column('movie_id',
                  sa.Integer().with_variant(sa.Integer(), 'sqlite'),
                  nullable=False),
        sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
        sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
        sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor_movie')
    # ### end Alembic commands ###
