"""empty message

Revision ID: f2d1d3e5451d
Revises: 8546009b8167
Create Date: 2020-05-26 11:44:12.276390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d1d3e5451d'
down_revision = '8546009b8167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'genre')
    # ### end Alembic commands ###
